mohdfawad99/hacktoberfest-2021

Python Programs/decimal_to_nbase_converter.py

Hello, this is my second pull request :D

decimal to nbase converter

---

Java Programs/LinearSearch.java

I added a new java code to find an element using linear search.

Java Linear Search Program

---

Python Programs/palindrome.py

#hacktoberfest #palindrome #hacktoberfest2021

Palindrome.py

---

C++ Programs/Allocation_of_house.cpp

array consists of rate of houses and limit represents the money you have to buy houses return

Count houses

---

Java Programs/SumOfDigits.java

I have changed the class name as you mentioned.
Thanks for pointing out the anomaly.

Modified SumOfDigit.java

---

Java Programs/Fibonacci,java
Java Programs/Fibonacci_nth.java

program to find nth fibonacci number

Added Fibonacci.java to find nth fibonacci number

---

C Programs/fibonacci_series.c

C Program to display Fibonacci series in a given range

Fibonacci series

---

C Programs/factorial_of_number.c

Factorial of a number

---

C++ Programs/Armstrong_number.cpp

#HacktoberFest2021  #Armstrong_number  #cpp

Created Armstrong_number.cpp

---

Java Programs/MergeSortNatural.java

Please add label "hacktoberfest-accepted" if merged

Add MergeSortNatural

---

Java Programs/FordFulkerson.java

Added Ford-Fulkerson Algorithm in java lang hope you support me by adding hacktoberfest label too

Added Ford-Fulkerson Algorithm in java

---

JavaScript Programs/pascal-case.js

Added implementation of pascal case converter method in javascript.

PascalCase converter method in javascript

---

Java Programs/Sort.java

Compare the time taken in Quick Sort, Merge Sort, Bubble Sort with huge dataset

Sorting Algorithms

---

Java Programs/BinarySearch.java
Java Programs/binarysearch.java

Binary Search Using Java,Error Fixed

Binary Search 

---

Codeforces Problems/A_Eshag_Loves_Big_Arrays.cpp

Problem Name - Eshag Loves Big Arrays
Eshag has an array a consisting of n integers.
Eshag can perform the following operation any number of times: choose some subsequence of a and delete every element from it which is strictly larger than AVG, where AVG is the average of the numbers in the chosen subsequence.
For example, if a=[1,4,3,2,4] and Eshag applies the operation to the subsequence containing a1, a2, a4 and a5, then he will delete those of these 4 elements which are larger than a1+a2+a4+a54=114, so after the operation, the array a will become a=[1,3,2].
Your task is to find the maximum number of elements Eshag can delete from the array a by applying the operation described above some number (maybe, zero) times.
A sequence b is a subsequence of an array c if b can be obtained from …

Codeforces Problem added

---

C Programs/neighbourhood_graph.c

Add Neighbourhood Graph Program on C Program

Add Neighbourhood Graph Program

---

bubblesort.cpp

I have added a bubble sort sorting algorithm written in C++ language for hacktoberfest as my first PR

added a bubble sort sorting method written in C++ language

---

C++ Programs/Element That Appears once.cpp

the following program find out the element that appears once in a sorted array of N size it follows a time complexity of o(log(n)) and space complexity of o(1)

Added program for element that appears once

---

C Programs/stringReverse.c

This is a C program to reverse a sentence using recursion

Added code to reverse sentence using recursion

---

C Programs/insertionSort.c

Added code is a C program for insertion sort along with time complexity analysis

Added C program for insertion sort with time analysis

---

C Programs/Knapsack.c

The code is a C program for Knapsack problem using greedy algorithm

Added a C Program for Knapsack problem

---

C++ Programs/Leaders in a array.cpp

The following program is the program for the leaders in an array. An element of array is leader if it is greater than or equal to all the elements to its right side. The rightmost element is always a leader.

Leaders in an array
